config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'bikes#index'
  resources :bikes do
    resources :bookings, except: [:index, :show]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :location, :price_per_day, presence: true
  validates :condition, numericality: { only_integer: true }
  validates :condition, inclusion: { in: 0..5 }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bikes
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bike_controller.rb
class BikeController < ApplicationController
  def index
    @bikes = Bike.all
  end
  def new
    @bike = Bike.new
  end
  def show
    @bike = Bike.find(params[:id])
  end
  def create
    @bike = Bike.new(bike_params)
  end
  def bike_params
    params.require(:bike).permit(:id, :location, :price_per_day, :condition, :type)
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @bikes = Bike.all
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude
      }
    end
    if params[:query].present?
      sql_subquery = <<~SQL
        bikes.location @@ :query
        OR bikes.category @@ :query
      SQL
      @bikes = @bikes.where(sql_subquery, query: params[:query])
    end
  end

  def new
    @bike = Bike.new
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def edit
    @bike=Bike.find(params[:id])
  end
  def update
    @bike = Bike.find(params[:id])
    if @bike.update(bike_params)
      redirect_to @bike, notice: 'Bike was successfully updated.'
    else
      render :edit
    end
  end
  def create
    puts params.inspect
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save

      redirect_to bike_path(@bike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:location, :price_per_day, :condition, :category, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_bike, except: [:index, :show]
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = @user
    @booking.save
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    set_booking
  end

  def edit
    set_booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to bike_booking_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :bike_id, :user_id)
  end

  def set_bike
    @bike = Bike.find(params[:bike_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_banner_bike.html.erb
<%= stylesheet_link_tag("banner_bike")%>

<div class="container">
  <div class="row align-items-center justify-content-md-center">
    <% @bike.photos.each do |photo| %>
      <div class="col-4">
        <div class="d-flex justify-content-center" id="image-div">
          <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bikes/_card_detail.html.erb
<%= stylesheet_link_tag("bike_index")%>

<div class="row">
  <% @bikes.each do |bike| %>
    <div class="col col-md-4 mt-3 mb-3">
      <div class="card" id="card-bike">
        <% if bike.photos.attached? %>
          <%= cl_image_tag bike.photos.first.key, class:"card-img-top" %>
        <% else %>
          <img src="https://coloringonly.com/images/imgcolor/Free-Bicycle-coloring-page.jpg" class="card-img-top" alt="Bike image">
        <% end %>

        <div class="card-body">
          <div class="d-flex justify-content-between mb-3">
            <div>
              <h5 class="card-title"><%= bike.location %></h5>
              <p class="card-text"><%= bike.category %></p>
              <p class="card-text"><%= number_to_currency(bike.price_per_day, unit: "£") %> per day</p>
            </div>
            <div>
              <p class="card-text"><%= bike.condition %></p>
            </div>
          </div>

          <div class="d-flex justify-content-between" id="div-links">
            <div>
            <%= link_to 'Book', new_bike_booking_path(bike) %>
            </div>
            <div>
            <%= link_to 'View Details', bike_path(bike) %>
            </div>
          </div>

        </div>
      </div>

    </div>
  <% end %>
</div>

app/views/bikes/_form.html.erb
  <%= simple_form_for @bike do |form| %>
    <%= form.error_notification %>

    <div class="form-inputs">
      <%= form.input :category %>
      <%= form.input :location %>
      <%= form.input :condition %>
      <%= form.input :price_per_day %>
      <%= form.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <span id="nav-btn">
      <%= link_to 'Back', bikes_path %>
      <%= form.submit class: 'btn btn-primary' %>
    </span>
  <% end %>

app/views/bikes/_searchbar.html.erb
<%= stylesheet_link_tag("bike_index")%>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: bikes_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/bikes/edit.html.erb
<%= stylesheet_link_tag("bike_new")%>

<div class="parent container d-flex flex-column align-items-center h-100">
  <h1>Edit your bike</h1>
  <%= simple_form_for @bike do |bike| %>
    <%= bike.error_notification %>

    <div class="form-inputs">
      <%= bike.input :location %>
      <%= bike.input :price_per_day %>
      <%= bike.input :category %>
      <%= bike.input :condition %>

    </div>

    <div class="form-actions" id="nav-btn">
      <%= link_to 'Back', bikes_path %>
      <%= bike.submit "Update", class: 'btn btn-primary'%>
    </div>
  <% end %>

</div>

app/views/bikes/index.html.erb
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<h1>Bikes in Your Area</h1>

<%= render "searchbar" %>
<div class="flexbox">
  <div class="bike-cards px-2">
  <%= render "card_detail" %>
  </div>

  <div class="map-card" style="width: 500px; height: 1200px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/bikes/new.html.erb
<%= stylesheet_link_tag("bike_new")%>

<div class="parent container d-flex flex-column align-items-center h-100">
  <h1>Create your new bike</h1>

  <%= render "form" %>
</div>

app/views/bikes/show.html.erb
<%= stylesheet_link_tag("bike_show")%>

<div class="parent container d-flex flex-column align-items-center h-100">
  <h1>Bike Details</h1>

  <%= render "banner_bike" %>

  <div class="container d-flex flex-column align-items-center h-100">
    <div class="d-flex felx-row bike-info">
      <div class="d-flex flex-column align-items-center justify-content-center">
        <p>Category</p>
        <span><%= @bike.category %></span>
      </div>
    </div>

    <div class="d-flex felx-row bike-info">
      <div class="d-flex flex-column align-items-center justify-content-center">
        <p>Location</p>
        <span><%= @bike.location %></span>
      </div>
    </div>

    <div class="d-flex felx-row bike-info">
      <div class="d-flex flex-column align-items-center justify-content-center">
        <p>Condition</p>
        <span><%= @bike.condition %></span>
      </div>
    </div>

    <div class="d-flex felx-row bike-info">
      <div class="d-flex flex-column align-items-center justify-content-center">
        <p>Price per Day</p>
        <span><%= number_to_currency(@bike.price_per_day, unit: "£") %></span>
      </div>
    </div>
  </div>

  <div class="container">
    <span id="nav-btn">
      <span id="back-btn"><%= link_to 'Back', bikes_path %></span>
      <span class="d-flex align-items-center justify-content-center" id="edit-btn"><%= link_to 'Edit', edit_bike_path(@bike) %></span>
    </span>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= stylesheet_link_tag("booking_new")%>
<div class="container">

  <h4 class="card-title mt-3"> Book your bike: <%=  @bike.category %></h4>
    <div class="back-link">
    <p><%= link_to 'Back to all bikes', bikes_path %></p>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="card p-2 m-2 card-booking">
      <img src="https://d1mo5ln9tjltxq.cloudfront.net/-/media/images/my23/bikes/road/endurance/synapse/tech-images/c23_synapsealloy_tech_0004.ashx?mh=2560&mw=1920&hash=C1DEADD7DE90FB022FDE5A6E51173ACE" class="card-img-top" alt="Bike image">
        <div class="card-body">
          <h5 class="card-title"><%= @bike.location %></h5>
          <p class="card-text"> <strong>Price per Day:</strong> £<%= @bike.price_per_day %></p>
          <p class="card-text"><strong>Category:</strong> <%= @bike.category %></p>
          <% condition = "<i class='fa-solid fa-star' style='color: #05b470;'></i>".html_safe %>
          <p class="card-text"><strong>Condition:</strong> <%= condition * @bike.condition  %></p>
          <%= link_to 'View Details', bike_path(@bike), class:'btn' %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card p-2 m-2 card-booking">
      <h5>Pick your dates!</h5>
        <div class="form">
          <%= simple_form_for [@bike, @booking] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date%>
            <%= f.submit "Amend", class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/bookings/index.html.erb
<%= stylesheet_link_tag('booking_index')%>

<div class="container">

  <h1>My bookings</h1>
  <div class="back-link">
    <%= link_to 'Back to bikes', bikes_path %>
  </div>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col col-md-4 ml-2 mr-2 mt-3 mb-3">
        <div class="card" class="card-booking">
          <img src="https://d1mo5ln9tjltxq.cloudfront.net/-/media/images/my23/bikes/road/endurance/synapse/tech-images/c23_synapsealloy_tech_0004.ashx?mh=2560&mw=1920&hash=C1DEADD7DE90FB022FDE5A6E51173ACE" class="card-img-top" alt="Bike image">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-3">
              <div>
                <h5 class="card-title booking-link"> <%= link_to  "Booking reference: #RAB24#{booking.id}", booking_path(booking) %> </h5>
                <p class="card-text"><%= booking.bike.location %> | <%= booking.bike.category %></p>
                  <div class="dates">
                  <p class="card-text"> <strong>Pick Up: </strong><%= booking.start_date%> </p>
                  <p class="card-text"> <strong>Drop off:</strong> <%= booking.end_date%> </p>
                  <% days = booking.end_date - booking.start_date %>
                  <% if days == 1 %>
                  <p>Bike booked for: <%= days.to_i %> day</p>
                    <% else %>
                  <p>Bike booked for: <%= days.to_i %> days</p>
                  <% end %>
                  </div>
              </div>
              <div>
                <p class="card-text"><strong>Total: </strong>£<%= booking.bike.price_per_day * days.to_i %></p>
              </div>
            </div>
            <div class="d-flex justify-content-between" id="div-links">
              <div>
              <%= link_to 'Amend',  edit_bike_booking_path(booking.bike, booking.id), class:'btn btn-flat' %>
              </div>
              <div>
              <%= link_to "Delete",
              bike_booking_path(booking.bike, booking),
              class:'btn btn-flat',
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
              %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= stylesheet_link_tag("booking_new")%>
<div class="container">

  <h4 class="card-title mt-3"> Book your bike: <%=  @bike.category %></h4>
    <div class="back-link">
    <p><%= link_to 'Back to all bikes', bikes_path %></p>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="card p-2 m-2 card-booking">
      <% if @bike.photos.attached? %>
          <%= cl_image_tag @bike.photos.first.key, class:"card-img-top" %>
        <% else %>
          <img src="https://coloringonly.com/images/imgcolor/Free-Bicycle-coloring-page.jpg" class="card-img-top" alt="Bike image">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @bike.location %></h5>
          <p class="card-text">Price per Day: £<%= @bike.price_per_day %></p>
          <p class="card-text">Category: <%= @bike.category %></p>
          <% condition = "<i class='fa-solid fa-star' style='color: #05b470;'></i>".html_safe %>
          <p class="card-text">Condition: <%= condition * @bike.condition  %></p>
          <%= link_to 'View Details', bike_path(@bike), class:'btn' %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card p-2 m-2 card-booking">
      <h5>Pick your dates!</h5>
        <div class="form">
          <%= simple_form_for [@bike, @booking] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date%>
            <%= f.submit "Book", class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/bookings/show.html.erb
<%= stylesheet_link_tag("booking_show")%>
<div class="container">

  <div class="booking-card-container">
    <h1>Your bike is booked!</h1>
    <div class="back-link">
    <%= link_to 'Back to bikes', bikes_path %>
  </div>
  <%# Booking card info  %>
    <div class="row">
      <div class="col-md-4 mb-4">
        <div class="card m-2 card-booking">
          <div class="card-body ">
            <h5 class="card-title"> Booking ref: #RAB24<%=  @booking.id %></h5>
                <div class="dates">
                  <p class="card-text"> <strong>Pick Up: </strong><%= @booking.start_date%> </p>
                  <p class="card-text"> <strong>Drop off:</strong> <%= @booking.end_date%> </p>
                  <% days = @booking.end_date - @booking.start_date %>
                  <% if days == 1 %>
                  <p>Bike booked for: <%= days.to_i %> day</p>
                    <% else %>
                  <p>Bike booked for: <%= days.to_i %> days</p>
                  <% end %>
                </div>
            <p class="card-text"> <strong>Total:</strong> £<%= @booking.bike.price_per_day %></p>
            <%= link_to 'See all my bookings', bookings_path, class: 'btn btn-flat' %>
          </div>
        </div>
      </div>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBikeProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p>Gilmar</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-brand d-flex align-items-center">
      <%= image_tag "https://cdn.iconscout.com/icon/premium/png-512-thumb/bike-location-2553072-2162982.png?f=webp&w=512" %>
       <span>BorrowMyBike</span>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://avatars.githubusercontent.com/gilmar-margoti", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", bikes_path, class: "dropdown-item" %>
              <%= link_to "New bike", new_bike_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>